# Generated by Django 6.0.6 on 2026-06-18 11:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Defensive: ensures the `vector` extension exists even if the
        # database container's initdb script hasn't run it yet. Our Docker
        # Postgres image already creates it on first boot, so this is a
        # no-op (CREATE EXTENSION IF NOT EXISTS) in the normal flow.
        VectorExtension(),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='ISO country code, e.g. BD, US', max_length=10, unique=True)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Country center point (auto-filled as the centroid of its properties on import)', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text="Property's geographic location", null=True, srid=4326)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Semantic-search embedding over name + description (populated later)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.location')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload a file directly (optional if a source `url` is provided instead)', null=True, upload_to='properties/%Y/%m/')),
                ('url', models.URLField(blank=True, help_text='Source image URL, e.g. from an imported CSV dataset', max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='property_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
