# Generated by Django 6.0.6 on 2026-06-23 05:04

import django.contrib.gis.db.models.fields
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_amenities_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Semantic embedding of location name (all-MiniLM-L6-v2)', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='property',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Semantic embedding from all-MiniLM-L6-v2 (384d)', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='location',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='location_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
